namespace AddinRibbon.Shapes
{
    public enum Direction
    {
        East,
        West,
        North,
        South,
        Up,
        Down,
        NorthEast,
        NorthWest,
        SouthEast,
        SouthWest,
        EastNorth,
        EastSouth,
        WestNorth,
        WestSouth,
        UpNorth,
        UpSouth,
        UpEast,
        UpWest,
        DownNorth,
        DownSouth,
        DownEast,
        DownWest,
        Unknown
    }
}
